version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app # Corrected typo
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL: mysql://directory:Directory123@192.168.1.101/directory
      LOKI: http://192.168.1.101:3100
      S3_ENDPOINT: 192.168.1.100
      S3_ACCESS_KEY: cFVms9i7n1weyt60gkZc
      S3_SECRET_KEY: xn8U6ABr20u90cfBnO5GIrv90IWcXe7fe0fyc7zt
