version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app # Corrected typo
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL: mysql://directory:dXnk.17DSw4TvpGx@192.168.1.101/directory
