const express = require('express')
const bodyParser = require('body-parser')
const client = require('prom-client')
const cors = require('cors')
const app = express()
const homeRoute = require('./routes/homeRoute')
const loginRoute = require('./routes/loginRoute')
const userRoute = require('./routes/userRoute')
const listRoute = require('./routes/listRoute')
const clubRoute = require('./routes/clubRoute')
const pageRoute = require('./routes/pageRoute')
const searchRoute = require('./routes/searchRoute')
const zoneRoute = require('./routes/zoneRoute')
const fileRoute = require('./routes/fileRoute')
const adminRoute = require('./routes/adminRoute')
const config = require('./config/config')
const { LogRequest } = require('./middleware/log')


app.use(cors())
app.use(LogRequest)
app.use(bodyParser.urlencoded({ extended: false }))
app.use(express.static("public"))
app.use('/api/login', loginRoute)
app.use('/api/home', homeRoute)
app.use('/api/user', userRoute)
app.use('/api/list', listRoute)
app.use('/api/club', clubRoute)
app.use('/api/page', pageRoute)
app.use('/api/search', searchRoute)
app.use('/api/zone', zoneRoute)
app.use('/file', fileRoute)
app.use('/api/admin', adminRoute)

app.get('/metrics', async (req, res) => {
    res.setHeader('Content-Type', client.register.contentType)
    const metrics = await client.register.metrics()
    res.send(metrics)
})
app.listen(config.port, '0.0.0.0', () => {
    console.log(`🚀 HTTP ${config.port}`)
})